sudo: required
language: rust
dist: bionic

rust:
    - nightly
    - beta
    - stable

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    rustup component add clippy
  fi

script:
  - |
      cargo update &&
      cargo build &&
      cargo test

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo clippy -- -D warnings
  fi
